---
# collections for cisco_network_scan role

collections:
  - name: cisco.ios
    source: https://galaxy.ansible.com
    version: 1.2.1

  # - name: clay584.genie
  #   source: https://galaxy.ansible.com
  #   version: 0.1.11
