---
# collections for cisco_network_scan role

collections:
  - name: cisco.ios
    source: https://galaxy.ansible.com
    version: 1.2.1

roles:
  - name: clay584.parse_genie
    source: https://galaxy.ansible.com
    version: 1.5.2
