---
- name: Check for online hosts
  hosts: all
  gather_facts: false
  connection: local
  vars:
    ansible_network_os: ios
    ansible_command_timeout: 30
    router_models: SR
    firewall_models: ASA

  tasks:
    - name: Ping for reachability
      command: ping -c2 {{ inventory_hostname }}
      delegate_to: localhost
      register: ping_result
      ignore_errors: true

    - name: Gather basic switch information
      ios_facts:
        gather_subset: min
      register: ios_result

    - name: Group hosts by online
      group_by: key=reachable
      when:
        - ping_result.rc == 0
        - ios_result.ansible_facts.ansible_net_model is defined
        - "'SR' not in ios_result.ansible_facts.ansible_net_model"
        - "'ASA' not in ios_result.ansible_facts.ansible_net_model"
      delegate_to: localhost

- name: Scan network
  hosts: reachable
  gather_facts: false
  connection: network_cli
  collections:
    - cisco.ios

  tasks:
    - include_role:
        name: cisco_network_scan
      vars:
        ansible_network_os: ios
