---
# handlers file for cisco_network_scan

- name: email report
  mail:
    from: "{{ from_email }}"
    to: "{{ email_addresses }}"
    port: "{{ smtp_port }}"
    subject: MAC Address Report {{ lookup('pipe','date +%Y-%m-%d') }}
    subtype: html
    host: "{{ smtp_server }}"
    attach: "{{ report_file }}"
  delegate_to: localhost
  run_once: true
  when:
    - smtp_server is defined
