---
# tasks file for cisco_network_scan

- name: Gather switch interface information
  ios_facts:
    gather_network_resources: l2_interfaces
  register: ios_interfaces_result

# parse information from devices in preparation for processing changes
- name: Parse Access Interface Data
  set_fact:
    interfaces_parsed: "{{ ios_interfaces_result.ansible_facts.ansible_network_resources | json_query(query) }}"
  vars:
    query: "l2_interfaces[].{name: name, vlan: access.vlan}"
  delegate_to: localhost