---
# tasks file for cisco_network_scan

- name: Gather switch interface information
  ios_facts:
    gather_network_resources: l2_interfaces
  register: ios_interfaces_result

# parse information from devices in preparation for processing changes
# - name: Parse Access Interface Data
#   set_fact:
#     interfaces_parsed: "{{ ios_interfaces_result.ansible_facts.ansible_network_resources }} | lookup('subelements', access, 'name')"

- name: Parse Access Interface Data
  set_fact:
    interfaces_parsed: item
  with_subelements:
    - "{{ ios_interfaces_result.ansible_facts.ansible_network_resources.l2_interfaces }}"
    - access

#FIXME not sure if when works
- name: Get mac address_table
  ios_command:
    lines:
      - "show mac address-table interfaces {{ item.name }}"
  when:
      - ios_interfaces_result.ansible_facts.ansible_net_interfaces[(lookup('var', 'item.name'))].operstatus == up
  with_items: interfaces_parsed
  register: mac_address_table
